---
title: "Margaret's markdown"
output:
 html_document:
   df_print: paged
---
```{r libraries}
library(tidyverse)
library(dplyr)
library(broom)
library(ggplot2)
library(stringr)
library(readr)
library(knitr)

```

```{r load-data, cache= TRUE}
training = read_csv("../../data/training_tallskinny.csv")
validation = read_csv("../../data/validation_tallskinny.csv")
interest_topics = read_csv("../../data/interest_topics.csv")

```


```{r small-sets, include = FALSE}

training_small <- training %>%
  slice(1:1000)
training_small

validation_small <- validation %>%
  slice(1:1000)
validation_small
topics_training_small <- left_join(training_small, interest_topics) %>%
  select(userID, inAudience, topic_name, everything())
```


```{r join}
topics_training <- left_join(training, interest_topics) %>%
  select(userID, inAudience, topic_name, everything())
```

```{r initial-graph}
true_training <- topics_training %>%
  group_by(topic_name) %>%
  count(inAudience) %>%
  filter(inAudience == TRUE) %>%
  arrange(desc(n)) %>%
  drop_na()
true_training %>%
  ggplot(aes(x = reorder(topic_name,-n), n)) +
  geom_bar(stat ="identity") +
   theme_void()
```

```{r catagorizing, cache = TRUE}
specL <- topics_training %>%
  mutate(topic_name = case_when(
    str_detect(topic_name, "/Arts & Entertainment") ~ "Arts & Entertainment",
    str_detect(topic_name, "/Autos & Vehicles") ~ "Autos & Vehicles",
    str_detect(topic_name, "/Beauty & Fitness") ~ "Beauty & Fitness",
    str_detect(topic_name, "/Books & Literature") ~ "Books & Literature",
    str_detect(topic_name, "/Business & Industrial") ~ "Business & Industrial",
    str_detect(topic_name, "/Computers & Electronics") ~ "Computers & Electronics",
    str_detect(topic_name, "/Finance") ~ "Finance",
    str_detect(topic_name, "/Food & Drink") ~ "Food & Drink",
    str_detect(topic_name, "/Games") ~ "Games",
    str_detect(topic_name, "/Health") ~ "Health",
    str_detect(topic_name, "/Hobbies & Leisure") ~ "Hobbies & Leisure",
    str_detect(topic_name, "/Home & Garden") ~ "Home & Garden",
    str_detect(topic_name, "/Internet & Telecom") ~ "Internet & Telecom",
    str_detect(topic_name, "/Jobs & Education") ~ "Jobs & Education",
    str_detect(topic_name, "/Law & Government") ~ "Law & Government",
    str_detect(topic_name, "/News") ~ "News",
    str_detect(topic_name, "/Online Communities") ~ "Online Communities",
    str_detect(topic_name, "/People & Society") ~ "People & Society",
    str_detect(topic_name, "/Pets & Animals") ~ "Pets & Animals",
    str_detect(topic_name, "/Real Estate") ~ "Real Estate",
    str_detect(topic_name, "/Reference") ~ "Reference",
    str_detect(topic_name, "/Science") ~ "Science",
    str_detect(topic_name, "/Shopping") ~ "Shopping",
    str_detect(topic_name, "/Sports") ~ "Sports",
    str_detect(topic_name, "/Travel") ~ "Travel",
    TRUE ~ as.character(topic_name)
  ))
```


```{r user-sums, include = FALSE}
specL %>%
  group_by(userID) %>%
  summarize(sumLt = sum(ltiFeatures)) %>%
  arrange(desc(sumLt))
```

```{r grouping-sum, cache = TRUE}
spec <- specL %>%
  group_by(userID, topic_name, inAudience) %>%
  drop_na() %>%
 summarize(totLti = sum(ltiFeatures),
           totSti = sum(stiFeatures))

```


```{r num-interests, cache = TRUE, include = FALSE}
spec_nums <- spec %>%
  group_by(userID) %>%
  count(userID)
names(spec_nums)[2] <- "num_interests"
spec_nums

spec <- left_join(spec, spec_nums)
spec %>%
  group_by(topic_name) %>%
  drop_na() %>%
 summarize(meanInt = mean(num_interests)) %>%
  arrange(desc(meanInt)) %>%
  ggplot(aes(x = reorder(topic_name,-meanInt), meanInt)) +
  geom_bar(stat ="identity") +
  coord_flip()
```


```{r gathering-test, cache = TRUE}
spec_true <- spec %>%
  group_by(topic_name) %>%
  count(inAudience) %>%
  filter(inAudience == TRUE) %>%
  select(topic_name, n)
names(spec_true)[2] <- "True"

spec_false <- spec %>%
  group_by(topic_name) %>%
  count(inAudience) %>%
  filter(inAudience == FALSE) %>%
  select(topic_name, n)
names(spec_false)[2] <- "False"
spec_gathered <- full_join(spec_true, spec_false)

spec_prop <- spec_gathered %>%
  mutate(prop = (True/(True + False))*100) %>%
  arrange(desc(prop))

spec_prop %>%
  arrange(prop) %>%
  ggplot(aes(x = reorder(topic_name,-prop), prop)) +
  geom_bar(stat ="identity") +
  coord_flip() +
  labs(y = "Conversion Rate (%)", x ="Topic", title = "Conversion Rates by Topic")

spec_true %>%
  ggplot(aes(x = reorder(topic_name,-True), True)) +
  geom_bar(stat ="identity") +
  coord_flip() +
  labs(y = "Number of users in audience", x ="Topic", title = "Audience nums by Topic")
  
```

```{r sum-interest, cache = TRUE}
spec %>%
  group_by(topic_name) %>%
  summarize(n = mean(totLti)) %>%
  arrange(desc(n)) %>%
  ggplot(aes(x = reorder(topic_name,-n), n)) +
  geom_bar(stat ="identity") +
  coord_flip() +
  labs(x = "Topic Catagory", y = "Average Interest Score (lt)", title = "for all entries")

spec %>%
  filter(inAudience == TRUE) %>%
  group_by(topic_name) %>%
  summarize(n = mean(totLti)) %>%
  arrange(desc(n)) %>%
  ggplot(aes(x = reorder(topic_name,-n), n)) +
  geom_bar(stat ="identity") +
  coord_flip() +
  labs(x = "Topic Catagory", y = "Average Interest Score (lt)", title = "for entries who have converted in the past")
```


```{r num-interests1}
spec_nums <- spec %>%
  group_by(userID) %>%
  count(userID)
names(spec_nums)[2] <- "num_interests"
spec_nums

spec <- left_join(spec, spec_nums)
spec %>%
  group_by(topic_name) %>%
  drop_na() %>%
 summarize(meanInt = mean(num_interests)) %>%
  arrange(desc(meanInt))
```

```{r true-num-ints}
spec %>%
  group_by(inAudience) %>%
  summarize(mean(num_interests))
```

```{r scatter-plot, cache = TRUE}
spec %>%
  ggplot(mapping = aes(x = totLti, y = totSti, color = topic_name)) +
  geom_smooth(method=lm, se = FALSE) +
  theme(legend.position = "none") +
  theme_minimal()

spec %>%
  ggplot(mapping = aes(x = totLti, y = totSti, color = topic_name)) +
  geom_point() +
  facet_wrap(~ topic_name) +
  theme_minimal() +
  theme(legend.position = "none")
```



