---
title: "Data Exploration"
author: Margaret Reed, Yi Chen, Caroline Maloney, Evelyn Cupil-Garcia
date: Nov 2, 2019
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(broom)
library(tidyverse)
library(knitr)
library(ggplot2)
```


```{r read-data, cache=TRUE, include=FALSE}
training = read_csv("../../data/training_tallskinny.csv")
validation = read_csv("../../data/validation_tallskinny.csv")
interest_topics = read_csv("../../data/interest_topics.csv")
```


## Adding a column of topic names to the dataframe

```{r addTopics}
training %>%
  names()

interest_topics %>%
  names()

user1 <- training %>%
  filter(userID == 1) 


user1Interest <- full_join(user1, interest_topics)
user1Interest$userID <- 1
user1Interest <- user1Interest %>%
  mutate_all(~replace(., is.na(.), 0))

joined <- full_join(training, interest_topics)
```


## Plotting conversion rates against topic names

```{r conversion-rate, fig.height=5, fig.width=7}

notConverted <- joined %>%
  group_by(topic_name) %>%
  count(inAudience) %>%
  filter(inAudience == FALSE) %>% 
  select(topic_name, n)

converted <- joined %>%
  group_by(topic_name) %>%
  count(inAudience) %>%
  filter(inAudience == TRUE) %>%
  select(topic_name, n)


names(notConverted)[2] <- "false"
names(converted)[2] <- "true"

both <- full_join(notConverted, converted)


both <- both %>%
  ungroup() %>%
  mutate(rate = true/(true + false))

both <- both %>%
  arrange(desc(rate)) %>%
  select(topic_name, rate) %>%
  slice(1:20) %>%
  arrange(desc(rate))

xlabs <- c("Symbian OS", "SEAT", "Kia", "Honda", "Hyundai", "Mazda", "Mitsubishi", "Nissan", 
           "Socially Responsible Investing", "Lincoln", "Subaru", "Buick", "Toyota", "Microcars & Subcompacts", 
           "Ink & Toner", "Cricket Equipment", "Acura", "Vehicle Shopping", "SUVs & Crossovers", "Retailers")

ggplot(both, mapping = aes(x = reorder(topic_name, rate), y = rate)) +
  geom_col() +
  coord_flip() + 
  labs(x = "Topic", 
       y= "Conversion Rate", 
       title = "Conversion rates by Subtopic") +
  scale_x_discrete(waiver(), labels = rev(xlabs)) + 
  theme_minimal()

```


```{r score_totals}
joined %>%
  drop_na() %>%
  group_by(topic_name) %>%
  summarise(sum = sum(ltiFeatures)) %>%
  arrange(desc(sum)) %>%
  ungroup()%>%
  slice(1:20) %>%
  ggplot(mapping = aes(x = reorder(topic_name, sum), y = sum)) +
    geom_col() + 
  coord_flip() + 
  labs(title = "Total Interest Scores for the Top 20 Topics", 
       x = "Topic", 
       y = "Total interest score") + 
  theme_minimal()
```



```{r score_average}
joined %>%
  drop_na() %>%
  group_by(topic_name) %>%
  summarise(average = mean(ltiFeatures)) %>%
  arrange(desc(average)) %>%
  ungroup()%>%
  slice(1:20) %>%
  ggplot(mapping = aes(x = reorder(topic_name, average), y = average)) +
  geom_col() + 
  coord_flip() + 
  labs(title = "Average Interest Scores Per User for the Top 20 Topics", 
       x = "Topic", 
       y = "Average interest score per user") + 
  theme_minimal()
```




